
# CircleCI configuration file
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  nothing:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: nothing
          command: |
            echo 'update deployment manifest'
