
# CircleCI configuration file
# See: https://circleci.com/docs/configuration-reference
version: 2.1

workflows:
  webhook:
    jobs:
      - deploy:
          context:
            - Github

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout

      - run:
          name: Update Manifest
          command: |
            set -x
            echo "Triggered by new image..."

            echo "install tools..."
            curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
            KUSTOMIZE=/home/circleci/project/kustomize
            echo "done"

            IMAGE_TAG=$(echo '<< pipeline.trigger_parameters.webhook.body >>' | jq -r '.push_data.tag')
            NAMESPACE=$(echo '<< pipeline.trigger_parameters.webhook.body >>' | jq -r '.repository.namespace')
            REPO_NAME=$(echo '<< pipeline.trigger_parameters.webhook.body >>' | jq -r '.repository.name')
            QUERY_URL="https://hub.docker.com/v2/namespaces/${NAMESPACE}/repositories/${REPO_NAME}/tags/${IMAGE_TAG}"
            
            echo "querying ${QUERY_URL}"
            DIGEST=$(curl -s -H 'Content-Type:application/json' ${QUERY_URL} | jq -r '.digest')
            echo "update nginx manifest digest to ${DIGEST} ..."

            cd ./infra/nginx-demo/kustomize/overlays/default
            # debug
            ls -la
            
            ${KUSTOMIZE} edit set image gnomesoft/nginx-demo=gnomesoft/nginx-demo@sha256:c67b65808de8ebbda8e09403b0904e635abd7decbd6d1576ba3b3e60d9ba9480

            git config user.email "roger.watkins@gnomesoft.co.uk"
            git config user.name "Circle CI"

            git checkout -b update-manifest-${IMAGE_TAG}
            git add -u .
            git commit -m "update manifest digest to ${DIGEST}"
            git push --force-with-lease origin update-manifest-${IMAGE_TAG}
  
      - run:
          name: Raise PR
          command: |
            set -x
            IMAGE_TAG=$(echo '<< pipeline.trigger_parameters.webhook.body >>' | jq -r '.push_data.tag')
            NAMESPACE=$(echo '<< pipeline.trigger_parameters.webhook.body >>' | jq -r '.repository.namespace')
            REPO_NAME=$(echo '<< pipeline.trigger_parameters.webhook.body >>' | jq -r '.repository.name')

            GH_USER=gnomesoftuk
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --url https://api.github.com/repos/${GH_USER}/${CIRCLE_PROJECT_REPONAME}/pulls \
            --data-binary @- \<< EOF
            {
                "title": "${REPO_NAME} image update: ${IMAGE_TAG}",
                "body": "Updated digest for image ${NAMESPACE}/${REPO_NAME}:${IMAGE_TAG}",
                "head": "update-manifest-${IMAGE_TAG}",
                "base": "${CIRCLE_BRANCH}"
            }
            EOF