
# CircleCI configuration file
# See: https://circleci.com/docs/configuration-reference
version: 2.1

workflows:
  webhook:
    jobs:
      - deploy

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout

      - run:
          name: update manifest
          command: |
            echo "Triggered by new image..."

            IMAGE_TAG=$(echo '<< pipeline.trigger_parameters.webhook.body >>' | jq -r '.push_data.tag')
            NAMESPACE=$(echo '<< pipeline.trigger_parameters.webhook.body >>' | jq -r '.repository.namespace')
            REPO_NAME=$(echo '<< pipeline.trigger_parameters.webhook.body >>' | jq -r '.repository.name')
            QUERY_URL="https://hub.docker.com/v2/namespaces/${NAMESPACE}/repositories/${REPO_NAME}/tags/${IMAGE_TAG}"
            
            echo "querying ${QUERY_URL}"
            DIGEST=$(curl -s -H 'Content-Type:application/json' ${QUERY_URL} | jq -r '.digest')
            echo "update nginx manifest digest to ${DIGEST} ..."

            cd ./infra/nginx-demo/kustomize/overlays/default
            kustomize edit set image gnomesoft/nginx-demo=gnomesoft/nginx-demo@sha256:c67b65808de8ebbda8e09403b0904e635abd7decbd6d1576ba3b3e60d9ba9480

            # TODO: pick this up next week and use the digest to rewrite the kustomize file and check it in

