apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nginx-depl.yaml

# transformers
commonAnnotations:
  author: rwatkins
  source: github.com/gnomesoftuk/nginx-demo
generatorOptions:
  immutable: true
labels:
- includeSelectors: true
  pairs:
    app: nginx-demo