apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-demo
    app.kubernetes.io/instance: nginx-demo
  name: nginx-demo-svc
  namespace: demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: nginx-demo
  type: NodePort