apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: nginx-depl.yaml
# rewrite and check this in to update images
images:
- digest: sha256:126fa68d029c5d4b7798ace8df2a2f6535d13086d20b14ba108b169ef99d1878
  name: gnomesoft/nginx-demo
  newName: gnomesoft/nginx-demo
