apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: nginx-depl.yaml
# rewrite and check this in to update images
images:
- digest: sha256:87dbb46478a71468c2d502e912fc6bdf9c7cbd4237aa50d81868525b2ae7828b
  name: gnomesoft/nginx-demo
  newName: gnomesoft/nginx-demo
