apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: nginx-depl.yaml
# rewrite and check this in to update images
images:
- digest: sha256:40ba93d8a7fdfba20bca26b01eda0bc0686cef5a58d63a1776a4ad886d7c928e
  name: gnomesoft/nginx-demo
  newName: gnomesoft/nginx-demo
