apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: nginx-depl.yaml
# rewrite and check this in to update images
images:
- digest: sha256:test
  name: gnomesoft/nginx-demo
  newName: gnomesoft/nginx-demo
